apiVersion: v1
kind: Service
metadata:
  name: fastfood-customer-service
  namespace: fastfood-customer
spec:
  selector:
    app: fastfood-customer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
