apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: customer-app
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
